project:
  type: book

book:
  title: "Resolução do Livro Fundamentos de Matemática Elementar"
  subtitle: "Volume 1: Conjuntos, Funções"
  author: "Igo da Costa Andrade"
  date: "10/04/2024"
  chapters:
    - index.qmd
    - chap-01.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    include-in-header: preamble.tex
    geometry:
      - top=30mm
      - left=30mm
      - right=20mm
      - bottom=20mm
    fontfamily: libertinus
    
    
lang: pt-br

editor: visual

